### ISSUE TITLE
 EEG Data download error

### ISSUE THREAD

**Issue by zanchangtong** [Deep-Learning-Qatar/EEG-Vision#1]

**Comment by zanchangtong** [comment]
![InkedC4QX K`JKC9V204HU_ `UZW_LI](https://user-images.githubusercontent.com/41229202/115647519-804d5a00-a356-11eb-9ebb-cb5363837436.jpg)

**Comment by stefanb0305** [comment]
https://tinyurl.com/eeg-visual-classification
